//
//  HomeVM.swift
//  Shadhin
//
//  Created by Joy on 10/10/22.
//  Copyright © 2022 Cloud 7 Limited. All rights reserved.
//

import UIKit

protocol HomeVMProtocol : NSObjectProtocol {
    func handleV3(patches:[HomeV3Patch])
    func handleAIPlaylists(aiPlaylists: [NewContent]?)
    func loading(isLoading: Bool, page: Int)
    func streamNwin(data : CampaignResponseNew)
    func concertData(data : ConcertEventObj)
    func refreshHome()
}

class HomeVM: NSObject {
    private weak var presenter : HomeVMProtocol?
    private var currentPage = 1
    private var totalPage = 2
    private var isLoading = false
    private var streamNwinCampaignResponse : StreamNwinCampaignResponse?
    private var campaignNewResponse : CampaignResponseNew?
    private var concertEventObj : ConcertEventObj?
    private var aiPlaylists: [NewContent]?
    
    init(presenter: HomeVMProtocol? = nil) {
        self.presenter = presenter
    }
    func reset(){
        currentPage = 1
        totalPage = 2
        isLoading = false
        streamNwinCampaignResponse = nil
        concertEventObj = nil
        loadHomeContent()
        loadRecomandedV3()
    }
}

extension HomeVM{
    func loadHomeContent(){
        guard !isLoading, currentPage <= totalPage else {return}
        self.isLoading.toggle()
        presenter?.loading(isLoading: self.isLoading, page: currentPage)
        getHomeContentV3(by: currentPage)
        if currentPage == 1{
            checkIfCampaignRunning()
        }
    }


    private func getHomeContentV3(by page: Int){
        ShadhinApi.Home.getHomeV3(by: page) {[weak self] data, error in
            guard let self = self else { return }
            if page == 1 {
                ShadhinCore.instance.api.getUserPlaylists { playlists, err in
                    let aiGeneratedPlaylists = playlists?.filter({$0.playlist?.autoGenerated == true})
                    if let aiGeneratedPlaylists, aiGeneratedPlaylists.isEmpty {
                        // do nothing
                    } else {
                        self.aiPlaylists = aiGeneratedPlaylists
                    }
                    DispatchQueue.main.async {
                        self.isLoading.toggle()
                        self.presenter?.loading(isLoading: self.isLoading, page: page)
                        guard let patches = data?.data else {return}
                        self.totalPage = data?.pagination?.totalPages ?? 2
                        self.currentPage += 1
                        self.presenter?.handleAIPlaylists(aiPlaylists: self.aiPlaylists)
                        self.presenter?.handleV3(patches: patches)
                    }
                    Log.info("Page : \(page)")
                }
            } else {
                DispatchQueue.main.async {
                    self.isLoading.toggle()
                    self.presenter?.loading(isLoading: self.isLoading, page: page)
                    guard let patches = data?.data else {return}
                    self.totalPage = data?.pagination?.totalPages ?? 2
                    self.currentPage += 1
                    self.presenter?.handleV3(patches: patches)
                }
                Log.info("Page : \(page)")
            }
        }
    }

    func frefreshAIPlaylists() {
        ShadhinCore.instance.api.getUserPlaylists { playlists, err in
            let aiGeneratedPlaylists = playlists?.filter({$0.playlist?.autoGenerated == true})
            if let aiGeneratedPlaylists, aiGeneratedPlaylists.isEmpty {
                // do nothing
            } else {
                self.aiPlaylists = aiGeneratedPlaylists
            }
            self.presenter?.handleAIPlaylists(aiPlaylists: self.aiPlaylists)
        }
    }
    

    func loadRecomandedV3(){
        let days = calculateDays()
        ShadhinApi.Home.getRecomandedHomeV3(days: days){ data, error in
            guard let patches = data?.data else {return}
            self.presenter?.handleV3(patches: patches)
        }
    }
    
    func calculateDays(from startDate: Date = Date()) -> String {
        // Define the target date
        let targetDate = Date() // Replace with your specific target date if needed
        
        // Calculate the difference in days
        let calendar = Calendar.current
        guard let days = calendar.dateComponents([.day], from: startDate, to: targetDate).day else {
            return "1" // Default to "1" if calculation fails
        }
        
        // Return the absolute value of days (to handle past or future dates)
        return String(abs(days))
    }
    private func checkIfCampaignRunning(){
        ShadhinCore.instance.api.getRunningCampaigns {
            campaigns in
            if campaigns.contains("MusicLiveEvent"){
                self.getConcertData()
            }
            if campaigns.contains("Stream_And_Win"){
                self.getStreamAndWinData()
            }
        }
    }
    
    private func getStreamAndWinData(){
        if self.streamNwinCampaignResponse != nil{
          //  self.insertStreamAndWinData()
            return
        }
        
        ShadhinCore.instance.api.getStreamAndWinCampaignActiveData() {
            result in
            switch result {
            case .success(let data):
                print("data")
                self.campaignNewResponse = data
                self.presenter?.streamNwin(data: data)
            case .failure(let error):
                Log.error(error.localizedDescription)
            }
        }
    }

    private func getConcertData(){
        if self.concertEventObj != nil{
            return
        }
        ShadhinCore.instance.api.getConcertEventsDetails { _eventData in
            guard let eventData = _eventData else {return}
            self.concertEventObj = eventData
            self.presenter?.concertData(data: eventData)
        }
    }

}


extension UIApplication {
    var currentWindow: UIWindow? {
        if #available(iOS 15.0, *) {
            return self.connectedScenes
                .compactMap { $0 as? UIWindowScene }
                .flatMap { $0.windows }
                .first { $0.isKeyWindow }
        } else {
            return self.windows.first { $0.isKeyWindow }
        }
    }
}
